### ISSUE TITLE
Incorrect Recipe for Spellbooks

### ISSUE THREAD

**Issue by xilef310** [iron431/all-the-wizard-armor#10]
Possible Fixes
Yes

Modpack Version
9-0.3.2

What happened?
I was looking up the best Spellbooks from this Mod and noticed that there is no valid Recipe displayed.
It a looped recipe. the book im trying to look the recipe up for is both the ingredient and result of the recipe.
I imagine its the same order like in the quest in which the books would need to be upgraded. the JEI doesnt display it as such.
I didnt try to actually craft them. im not that far yet.

latest.log
No response

Developer reports
No response

**Comment by iron431** [comment]
recipes required the Allthemodium mod
