### ISSUE TITLE
All the Wizard keeps crashing the moment i click on the singleplayer button

### ISSUE THREAD

**Issue by Brokenspace666** [iron431/all-the-wizard-armor#2]
NVM couldnt fix this stupid bug

[crash-2023-11-04_00.15.56-client.txt](https://github.com/iron431/all-the-wizard-armor/files/13255121/crash-2023-11-04_00.15.56-client.txt)
[latest.log](https://github.com/iron431/all-the-wizard-armor/files/13255122/latest.log)

**Comment by iron431** [comment]
you need to install All the Ores, which is a dependency of Allthemodium
