### ISSUE TITLE
Unobtainium wizard gear doesn't have full fire immunity

### ISSUE THREAD

**Issue by iHeroLix** [iron431/all-the-wizard-armor#3]
Unobtainium wizard gear doesn't have full fire immunity like it's equivalent armor counterpart does, equipping any single unobtainium armor piece grants full fire immunity, meaning fire damage and lava no longer has any effect. 
That's not the case when using any single unobtainium wizard gear.

**Comment by iHeroLix** [comment]
Just to add, it's not fall damage immune either while Unobtainium armor is

**Comment by iron431** [comment]
It also seems the original armor gives water breathing too. I'll release a patch for these when I have time, within the next few days

**Comment by iHeroLix** [comment]
It's probably best to check on Modium tier wizard gear and Vibranium tier wizard gear

**Comment by iron431** [comment]
Fixed in latest version
