### ISSUE TITLE
Crash in rendering 

### ISSUE THREAD

**Issue by Swantsy** [iron431/all-the-wizard-armor#4]
in ATM9 version 0.2.28 
It keeps giving an error message and occasional crash

https://api.paste.ee/p/1YOxP

Here is the link to the entire log.
Registry Object not present: allthewizardgear:allthemodium_mage_helmet looks to be the problem to narrow it down.

**Comment by iron431** [comment]
> at com.minecolonies.api.compatibility.CompatibilityManager.discoverAllItems(CompatibilityManager.java:633) ~[minecolonies-1.20.1-1.1.344-BETA.jar%23754!/:1.20.1-1.1.344-BETA] {re:classloading}

This looks like an issue with minecolonies attempting to load our registry before our mod has loaded. You should also report this to them. I would have to look into this further to see if there's anything I can do on my end
